//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketSQLite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReport
    {
        public long Id { get; set; }
        public string ProductName { get; set; }
        public long ProductId { get; set; }
        public string VendorName { get; set; }
        public long TotalQuantitySold { get; set; }
        public decimal TotalIncomes { get; set; }
    }
}
