//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketSQLite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public string Product_Name { get; set; }
        public decimal Tax1 { get; set; }
        public long Id { get; set; }
    }
}
