//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public long WorkHoursLogId { get; set; }
        public System.DateTime CommandDateTime { get; set; }
        public string CommandType { get; set; }
        public long WorkHourId { get; set; }
        public Nullable<long> OldWorkHourId { get; set; }
        public Nullable<System.DateTime> OldWorkDate { get; set; }
        public string OldTask { get; set; }
        public string OldComments { get; set; }
        public Nullable<int> OldWorkHours { get; set; }
        public int OldEmployeeId { get; set; }
        public Nullable<long> NewWorkHourId { get; set; }
        public Nullable<System.DateTime> NewWorkDate { get; set; }
        public string NewTask { get; set; }
        public string NewComments { get; set; }
        public Nullable<int> NewWorkHours { get; set; }
        public int NewEmployeeId { get; set; }
    
        public virtual WorkHour WorkHour { get; set; }
    }
}
